name = "pphi2"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Pphi2"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a â†¦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "OSforGFF"
path = "../OSforGFF-dimensions"

[[require]]
name = "GaussianField"
path = "../gaussian-field"

[[lean_lib]]
name = "Pphi2"
